Survey Form Review
ridaarif98/SurveyFormReview pull request #1
Opened 2021-06-02 09:55 UTC by ridaarif98

In this Survey Review,
      I add markup for the Index page
     Remove Inline style in the Index page
      Link Index page with a stylesheet
     Integrate Linters to Survey Review Form

2021-06-02 10:49 UTC, ridaarif98 reviewed
Good Job! You try hard. But there are still some linter errors.
Please try to Resolve linetrs error in the stylesheet.

2021-06-02 21:10 UTC, bolah2009 requested changes
Hi @ridaarif98,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

1. You should have at least 2 comments in the review. Currently, there's only one. Please re-do this review.
2. You should use the GitHub inline comment. See the example inline comment review below.
3. You should be polite and clear in your comments, this helps with effective communication. In summary, let's start comments with "I think ..." or any other polite phrases to make communication polite. Also, let's add reasons "why" a change is been requested/suggested and make sure your comment is clear and not vague. See this article on [How to give a code review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md) for ore details

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- A nice tip to consolidate your reviews under a single summary is to click the "Start a review" button when adding the first review comment. This helps to house all your inline comment under one single summary like this current review. 😉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-02 21:10 UTC, bolah2009 commented on Index.html
> +                  <p></p><p></p>
This is an example inline comment. 🙂 

You can see how it's under the main summary above and point to a specific part of the code where you want to suggest changes or just comment on it generally. 😉

2021-06-03 06:25 UTC, ridaarif98 reviewed
Good job so far! but you know there is always room for improvements, there are some issues that you still need to work on to go to the next project but you are almost there!
 Please make sure your Markup is clear giving an idea to the reader the purpose of each tag.
Also, make sure that your classes name should be meaningfull

2021-06-03 06:25 UTC, ridaarif98 commented on Index.html
> +              <div class="row" style="padding-top: 50px; padding-bottom: 50px; background-color: midnightblue; border-radius: 10px;">
Style is supposed to be inside stylesheet.

2021-06-03 06:25 UTC, ridaarif98 commented on Index.html
> +                    <label for="exampleFormControlTextarea1">Any comments or suggestions?</label>
You try hard. But there is always a pace to improve. 
'For' value must be similar to Id of the hidden element.

2021-06-03 06:25 UTC, ridaarif98 commented on Index.html
> +                    <input type="submit" id="submit" class="btn-success" class="form-control" value="Submit" />
Please remove duplicate 'class' attribute

2021-06-03 06:25 UTC, ridaarif98 commented on style.css
> +
Your code looks much better, I like it.But I think you adjust the spaces so it looks more professional

2021-06-03 06:25 UTC, ridaarif98 commented on Index.html
> +</html>
You try hard and its looks good. But still, you can improve it. Instead of div, you can use header ,nav ,section

2021-06-03 11:10 UTC, nidalaa commented on Index.html
> +              <div class="row" style="padding-top: 50px; padding-bottom: 50px; background-color: midnightblue; border-radius: 10px;">
Hi @ridaarif98 , great usage of inline comments. The only one thing that is missing in your review is an explanation **why** you suggest a given change. Even if something is super obvious for you it might not be to someone else.

For example here you could say:

> Style is supposed to be inside stylesheet. Thanks to that your code will be cleaner and easier to understand.

2021-06-03 11:12 UTC, nidalaa commented on Index.html
> +                    <label for="exampleFormControlTextarea1">Any comments or suggestions?</label>
Similar to the previous comment, you are missing the explanation - **why** this change is requested?

E.g.:


>You try hard. But there is always a pace to improve.
>'For' value must be similar to Id of the hidden element. Thanks to that it will be easier to understand which elements are connected to each other.

2021-06-03 11:16 UTC, nidalaa commented on Index.html
> +                    <input type="submit" id="submit" class="btn-success" class="form-control" value="Submit" />
Similar to the previous comment, you are missing the explanation - **why** this change is requested?
Also, this comment sounds more like an order, not a suggestion (please refer to [How to communicate?](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md#how-to-communicate)).

Here is how you could improve it:

>It would be better to remove the duplicate 'class' attribute. You can simply use two class names inside one class attribute `class="btn-success form control"`. Thanks to that you will keep all class information in one place.

2021-06-03 11:17 UTC, nidalaa commented on Index.html
> +</html>
Similar to the previous comment, you are missing the explanation - why this change is requested?

would you be able to rephrase that comment by yourself @ridaarif98  ?

2021-06-03 11:20 UTC, nidalaa approved these changes
Hi  @ridaarif98 , 

You have addressed all comments from the previous reviewer:
- You left more than 2 inline comments in your review
- You used inline comments
- You tried to be polite and clear in your comments. They could still be better by giving more context and explanation why a given change is requested - please check my comments below your comments for more details.

Nothing from above is topping me from saying that your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Students Handbook](https://www.notion.so/microverse/Project-reviews-022203ea6dd944b296b005533a19dcbe#cb67391d09f54bd98d6fed6ba24a4074) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 11:38 UTC, merged